### ISSUE TITLE
1.1.0 broke semver for us.

### ISSUE THREAD

**Issue by ddombrow** [cjlarose/argon2-ffi#25]
So... I believe 1.1.0 breaks builds that have a caret ^1.0.0 in their package.json.  When we got the new version of this package it would not compile on node 6.  Isn't NAPI a new node feature?

**Comment by addaleax** [comment]
>  Isn't NAPI a new node feature?

It is, but the npm package for it comes with a fallback for Node 4 & 6.

Can you share the actual error you’re seeing? I’m sorry you were running into trouble but we’ll be really glad to help that get fixed.

**Comment by ddombrow** [comment]
Here's some error output this is with node version = 6.11.1 and npm version = 3.10.10

```> ffi-napi@2.4.1 install /Users/dandombrowsky/src/account-service/node_modules/ffi-napi
> node-gyp rebuild

clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
gyp: Call to './configure --enable-static --disable-shared --disable-builddir --with-pic' returned exit status 0 while in deps/libffi/libffi.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/dandombrowsky/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 17.3.0
gyp ERR! command "/Users/dandombrowsky/.nvm/versions/node/v6.11.1/bin/node" "/Users/dandombrowsky/.nvm/versions/node/v6.11.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/dandombrowsky/src/account-service/node_modules/ffi-napi
gyp ERR! node -v v6.11.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm ERR! Darwin 17.3.0
npm ERR! argv "/Users/dandombrowsky/.nvm/versions/node/v6.11.1/bin/node" "/Users/dandombrowsky/.nvm/versions/node/v6.11.1/bin/npm" "install" "--save" "argon2-ffi@1.1.0"
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

We just pinned the package.json at 1.0.0 for now in our repo.

**Comment by addaleax** [comment]
@ddombrow Could you try again? I had tried merging https://github.com/node-ffi/node-ffi/pull/285 (from the original `node-ffi`) into the N-API variant, and since that seems like the most likely candidate for this issue it’s reverted now in `node-ffi-napi@2.4.2`.

**Comment by cjlarose** [comment]
Closing due to inactivity. If there's still a problem on the latest version, please reopen!
