### ISSUE TITLE
Cannot run in AWS Lambda

### ISSUE THREAD

**Issue by patrickmuhi** [cjlarose/argon2-ffi#26]
How do you build a static library of this, for AWS Lambda environment,

I tried building it from Amazon linux, then deployed my lambda but i get the same native error, 

```
module initialization error: Error
at Error (native)
at Object.Module._extensions..node (module.js:597:18)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at bindings (/var/task/node_modules/bindings/bindings.js:81:44)
at Object.<anonymous> (/var/task/node_modules/ref-napi/lib/ref.js:7:47)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (/var/task/node_modules/argon2-ffi/lib/index.js:10:16)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
```

**Comment by cjlarose** [comment]
@addaleax Have you seen this error before?

**Comment by addaleax** [comment]
No … :/ @pmuhire Can you share steps to reproduce this? Did this error just start to occur? Are you having the same kind of trouble with `argon2-ffi@1.0.1`?

**Comment by patrickmuhi** [comment]
@addaleax the library works on a typical server environment, but once you package it and deploy it to aws lambda, it shows that error.

At first i thought i was packaging it from a wrong architecture(ubuntu 14), but then i built my app from an Amazon linux instance, which is similar to the lambda environment but still got the same error.

This is what i did, 
- I wrote a simple app that includes this library
- npm install
- zip the `node_modules` and my index file, then uploaded it to lambda

node version:   6.10.0

**Comment by addaleax** [comment]
@pmuhire Could you share that .zip?

**Comment by patrickmuhi** [comment]
@addaleax Thanks a lot for the help. i think i upgraded to a new version then it worked.

**Comment by addaleax** [comment]
@pmuhire Just so we can know in the future, new version of what?

**Comment by patrickmuhi** [comment]
@addaleax Sure, version `1.0.1` didn't work , i upgraded to `1.1.0` then it ran smooth.
