### ISSUE TITLE
Unable to load 1.1.1 on Windows.

### ISSUE THREAD

**Issue by codingchili** [cjlarose/argon2-ffi#34]
Building and running tests on 1.1.0 works fine.
Building 1.1.1 and running tests on breaks.

Only affects Windows builds.

```
C:\documents\private\kbn-auth>mocha test -u tdd --recursive
C:\documents\private\kbn-auth\node_modules\ffi-napi\lib\dynamic_library.js:74
    throw new Error('Dynamic Linking Error: ' + err);
    ^

Error: Dynamic Linking Error: Win32 error 126
    at new DynamicLibrary (C:\documents\private\kbn-auth\node_modules\ffi-napi\lib\dynamic_library.js:74:11)
    at new Library (C:\documents\private\kbn-auth\node_modules\ffi-napi\lib\library.js:45:14)
    at Object.<anonymous> (C:\documents\private\kbn-auth\node_modules\argon2-ffi\lib\library.js:23:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\documents\private\kbn-auth\node_modules\argon2-ffi\lib\index.js:14:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\documents\private\kbn-auth\src\authentication\hash.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\documents\private\kbn-auth\src\authentication\file.js:8:14)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\documents\private\kbn-auth\src\authentication\twofactor.js:14:17)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\documents\private\kbn-auth\src\api\api.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\documents\private\kbn-auth\test\api\api.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at C:\Users\robdu\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:230:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\robdu\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:227:14)
    at Mocha.run (C:\Users\robdu\AppData\Roaming\npm\node_modules\mocha\lib\mocha.js:495:10)
    at Object.<anonymous> (C:\Users\robdu\AppData\Roaming\npm\node_modules\mocha\bin\_mocha:469:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
```

Using node 10.15.1.

This are the only changes I found in the 1.1.1 release, why does this break on windows?
https://github.com/cjlarose/argon2-ffi/pull/32

**Comment by cjlarose** [comment]
Thanks so much for narrowing down the change that broke for you. I think 1.1.1 also broke macOS for some people. It has to do with the path of the dynamic library file that's generated for libargon2. That path is different on different platforms. I'll see if I can put together a fix and I'll have to rely on you for building it and seeing if it works for you.

**Comment by cjlarose** [comment]
@codingchili Can you see if version 1.1.2 works for you on Windows?

**Comment by codingchili** [comment]
Thanks! 

1.1.2 works on windows 🥇 

```
  Generating code
  All 78 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  Finished generating code
  argon2.vcxproj -> C:\documents\private\kbn-auth\node_modules\argon2-ffi\build\Release\\argon2.dll
  argon2.vcxproj -> C:\documents\private\kbn-auth\node_modules\argon2-ffi\build\Release\argon2.pdb (Full PDB)
```

And all tests passing.
