### ISSUE TITLE
Unable to install argon2-ffi with npm

### ISSUE THREAD

**Issue by RobertWLeslie** [cjlarose/argon2-ffi#59]
OS: Ubuntu 20.04
node version: 10.19.0
npm version: 6.14.4
python version: 2.7.18

```> ref-napi@2.1.2 install /home/xx/Documents/xx/xx/node_modules/ffi-napi/node_modules/ref-napi
> node-gyp-build


> ffi-napi@3.1.0 install /home/xxx/Documents/xx/xx/node_modules/ffi-napi
> node-gyp-build

make: Entering directory '/home/xx/Documents/xx/xx/node_modules/ffi-napi/build'
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CC(target) Release/obj.target/ffi/deps/libffi/src/prep_cif.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/types.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/java_raw_api.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/closures.o
../deps/libffi/src/closures.c: In function ‘dlmmap_locked’:
../deps/libffi/src/closures.c:421:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
  421 |       ftruncate (execfd, offset);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
../deps/libffi/src/closures.c:433:7: warning: ignoring return value of ‘ftruncate’, declared with attribute warn_unused_result [-Wunused-result]
  433 |       ftruncate (execfd, offset);
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/ffi64.o
../deps/libffi/src/x86/ffi64.c: In function ‘classify_argument’:
../deps/libffi/src/x86/ffi64.c:181:18: warning: suggest braces around empty body in an ‘else’ statement [-Wempty-body]
  181 |    FFI_ASSERT (0);
      |                  ^
../deps/libffi/src/x86/ffi64.c:156:7: warning: this statement may fall through [-Wimplicit-fallthrough=]
  156 |       {
      |       ^
../deps/libffi/src/x86/ffi64.c:183:5: note: here
  183 |     case FFI_TYPE_FLOAT:
      |     ^~~~
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/unix64.o
  CC(target) Release/obj.target/ffi/deps/libffi/src/x86/sysv.o
  AR(target) Release/obj.target/deps/libffi/libffi.a
  COPY Release/libffi.a
  CXX(target) Release/obj.target/ffi_bindings/src/ffi.o
../src/ffi.cc: In static member function ‘static FFI::InstanceData* FFI::InstanceData::Get(Napi::Env)’:
../src/ffi.cc:11:24: error: ‘napi_get_instance_data’ was not declared in this scope; did you mean ‘napi_new_instance’?
   11 |   napi_status status = napi_get_instance_data(env, &d);
      |                        ^~~~~~~~~~~~~~~~~~~~~~
      |                        napi_new_instance
../src/ffi.cc: In function ‘Napi::Object BindingHook(Napi::Env, Napi::Object)’:
../src/ffi.cc:347:24: error: ‘napi_set_instance_data’ was not declared in this scope; did you mean ‘napi_new_instance’?
  347 |   napi_status status = napi_set_instance_data(
      |                        ^~~~~~~~~~~~~~~~~~~~~~
      |                        napi_new_instance
make: *** [ffi_bindings.target.mk:116: Release/obj.target/ffi_bindings/src/ffi.o] Error 1
make: Leaving directory '/home/x/Documents/xx/xx/node_modules/ffi-napi/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/nodejs/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.8.0-43-generic
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/xx/Documents/xx/xx/node_modules/ffi-napi
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
npm WARN xx@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ffi-napi@3.1.0 install: `node-gyp-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffi-napi@3.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.```

**Comment by cjlarose** [comment]
The error message indicates that `ffi-napi` failed to build. `ffi-napi` is a dependency of `argon2-ffi`, but I think this issue is better suited for that project.

https://github.com/node-ffi-napi/node-ffi-napi/issues/91 looks related. In that particular issue, the issue reporter ended up upgrading from Node 10 to Node 12, but that shouldn't have been necessary since `ffi-napi` doesn't require Node 12.

Can you repost this issue the `ffi-napi` project? https://github.com/node-ffi-napi/node-ffi-napi/issues
